modLoader = "kotori_scala"
loaderVersion = "[2.13.3-bluid-7,)"
license = "All rights reserved"
issueTrackerURL = "https://github.com/Kotori316/SLP-Mixin/issues/"

[[mods]]
modId = "slp-mixin"
version = "${file.jarVersion}"
displayName = "SLP Mixin"
credits = "Thanks for this example mod goes to Java"
authors = "Kotori316"
description = '''
Plugin of Scalable Cat's Force.'''

[[dependencies.slp-mixin]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.slp-mixin]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.4,1.17)"
ordering = "NONE"
side = "BOTH"
