# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "1.16" ]
  pull_request:
    branches: [ "1.16" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: download_assets
      run: ./gradlew downloadAssets || ./gradlew downloadAssets || (sleep 30s && ./gradlew downloadAssets)
      continue-on-error: true
    - name: Test JUnit
      run: ./gradlew test --no-daemon --continue --warning-mode all
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
    - name: Test runData
      run: chmod +x ./gradlew && ./gradlew runData --no-daemon
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
    - name: Check started and errore
      run: |
        [ -f test_started.txt ]
        ! [ -f error-trace.txt ]
    - id: show-failure-log
      if: failure()
      run: cat error-trace.txt

